### PR TITLE
Added TI LM74 temperature sensor example 

### PR DESCRIPTION
**Pull request by matejperejda**
I've added new example of temperature measurement via **Texas Instruments LM74** temperature sensor that was previously implemented to the Bulldog library.

### CODE REVIEW

**Comment by sbunciak** [comment]
@matejperejda squash commits

**Comment by sbunciak** [comment]
@matejperejda reason for closing?

**Comment by matejperejda** [comment]
@sbunciak I've tried to squash those commits but couldn't solve it. When I call `git push -f` it will close the pull request.

**Comment by matejperejda** [comment]
@sbunciak Commits were squashed just in my forked repo. [https://github.com/matejperejda/bulldog-examples/commits/master](url)

**Comment by mijaros** [comment]
You have squashed whole commit history of bulldog. When you're squashing
you should squash only commits that are bonded together, not whole
history of commits.

Your PR is unmergable with bulldog, hence github found, that it's
irrelevant and closed the PR.

Please try to reset your local repository to state before squash, and
then squash only commits in line, that are really implementing the
changes, not the commits you didn't make.


Best regards

Mirek

**Comment by mijaros** [comment]
Mea clupa, you didn't remove commits, I looked wrong repo. But you've still managed to rewrite commits somehow. If you'll look to the commit hashes, you'll see, that all of them differs, so the process of solution sitll applies, you need to reset your work, and do the squash again and properly.

**Comment by matejperejda** [comment]
@sbunciak @mijaros Thank you. I solved it and created new PR.

**Pull request closed without merging**
